# This is a basic workflow that is manually triggered

name: TestPROGPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
       # list contents or directory
      - name: List contents
        run: ls
     # Compiles classes to test 
      - name: compile classes
        working-directory: ./src/prog5121poe
        run: javac -cp "../../testresources/junit-platform-console-standalone-1.8.2.jar" ./loginp2/LoginP2.java "./../test/test/TaskNGTest.java"  "./../test/test/LoginP2NGTest.java"  

    # list contents of src to verify that classess compiled 
      - name: List contents of src directory after compile
        working-directory: ./src/loginp2
        run: ls
        
        
       # copy compiled classes to test directory 
      - name : copy compiled classes to testresources directory 
        working-directory: ./src/test
        run: cp -t  "../../test/test" loginp2.class LoginP2.class
        
        #copy compiled tests 
      - name : copy compiled Test classes to testresources directory 
        working-directory: ./test/test
        run: cp -t  "../../testresources/" loginp2.class Loginp2.class
        
        # list contents or directory
      - name: List contents test package
        working-directory: ./test/test
        run: ls
        
        #run tests and output report 
      - name: run tests and create report 
        working-directory: ./test
        run: java  "../testresources/junit-platform-suite-commons-1.8.2.jar:../testresources/junit-platform-suite-api-1.8.2.jar:../testresources/junit-platform-suite-engine-1.8.2:../testresources/juniorg.junit.platform.console.ConsoleLauncher " -cp "./prog5121poe" --select-class TaskTest  --reports-dir ="reports"
Is
java -jar/testresources/ junit-platform-console-standalone-1.6.0. jarcP-select-class test.TaskNGTest
